name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MY_VAR: ${{ secrets.MY_VAR }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: MY_VAR, DB_URL, JWT_SECRET
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 stop my-app
            cd hacksharktank
            git reset --hard
            git pull origin main
            npm install
            pm2 start --update-env my-app
